// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvfxDLoHArPyZqta0CfLqzNJJA2u5f_4I',
    appId: '1:921125766812:android:01ab98718388b4515d0f59',
    messagingSenderId: '921125766812',
    projectId: 'attendance-system-92c87',
    storageBucket: 'attendance-system-92c87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCau6beXh97OEGfCXrcdtgmfPdoHULs7Bs',
    appId: '1:921125766812:ios:f5a30c8d96ac77bd5d0f59',
    messagingSenderId: '921125766812',
    projectId: 'attendance-system-92c87',
    storageBucket: 'attendance-system-92c87.appspot.com',
    androidClientId: '921125766812-8t66shtl6gj5hra2iegbb7s316lafvni.apps.googleusercontent.com',
    iosClientId: '921125766812-k6tk2preu9cel1gqua93kq3su7f7aank.apps.googleusercontent.com',
    iosBundleId: 'com.example.canndc',
  );
}
